### ISSUE TITLE
Bug With Add to QuickSend Intent

### ISSUE THREAD

**Issue by othreecodes** [othreecodes/Quicksend#1]
After adding a new Company Via the Add to QuickSend Intent, The Dialog comes back after Switching Tabs .

**Comment by BigBlackFella** [comment]
I haven't fully studied the code but I think there's a line in the HomeFragment class that says if data email != null it should perform the floating button action.  
![image](https://cloud.githubusercontent.com/assets/6196262/26101169/1a1748f4-3a28-11e7-92cf-b1411bc345ee.png)

**Comment by othreecodes** [comment]
@BigBlackFella Turns out setting `dataEmail` to null in that function after the email has been added, solves the problem. Thanks for pointing it out.
